package com.my.pojo;

import java.util.Date;

public class Checkresult {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checkresult.crid
     *
     * @mbggenerated Wed Feb 20 16:43:50 CST 2019
     */
    private Integer crid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checkresult.uid
     *
     * @mbggenerated Wed Feb 20 16:43:50 CST 2019
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checkresult.chtime
     *
     * @mbggenerated Wed Feb 20 16:43:50 CST 2019
     */
    private Date chtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checkresult.status
     *
     * @mbggenerated Wed Feb 20 16:43:50 CST 2019
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checkresult.chid
     *
     * @mbggenerated Wed Feb 20 16:43:50 CST 2019
     */
    private Integer chid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checkresult.crid
     *
     * @return the value of checkresult.crid
     *
     * @mbggenerated Wed Feb 20 16:43:50 CST 2019
     */
    public Integer getCrid() {
        return crid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checkresult.crid
     *
     * @param crid the value for checkresult.crid
     *
     * @mbggenerated Wed Feb 20 16:43:50 CST 2019
     */
    public void setCrid(Integer crid) {
        this.crid = crid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checkresult.uid
     *
     * @return the value of checkresult.uid
     *
     * @mbggenerated Wed Feb 20 16:43:50 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checkresult.uid
     *
     * @param uid the value for checkresult.uid
     *
     * @mbggenerated Wed Feb 20 16:43:50 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checkresult.chtime
     *
     * @return the value of checkresult.chtime
     *
     * @mbggenerated Wed Feb 20 16:43:50 CST 2019
     */
    public Date getChtime() {
        return chtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checkresult.chtime
     *
     * @param chtime the value for checkresult.chtime
     *
     * @mbggenerated Wed Feb 20 16:43:50 CST 2019
     */
    public void setChtime(Date chtime) {
        this.chtime = chtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checkresult.status
     *
     * @return the value of checkresult.status
     *
     * @mbggenerated Wed Feb 20 16:43:50 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checkresult.status
     *
     * @param status the value for checkresult.status
     *
     * @mbggenerated Wed Feb 20 16:43:50 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checkresult.chid
     *
     * @return the value of checkresult.chid
     *
     * @mbggenerated Wed Feb 20 16:43:50 CST 2019
     */
    public Integer getChid() {
        return chid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checkresult.chid
     *
     * @param chid the value for checkresult.chid
     *
     * @mbggenerated Wed Feb 20 16:43:50 CST 2019
     */
    public void setChid(Integer chid) {
        this.chid = chid;
    }
}