package com.my.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CheckresultExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table checkresult
     *
     * @mbggenerated Wed Feb 20 16:43:50 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table checkresult
     *
     * @mbggenerated Wed Feb 20 16:43:50 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table checkresult
     *
     * @mbggenerated Wed Feb 20 16:43:50 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkresult
     *
     * @mbggenerated Wed Feb 20 16:43:50 CST 2019
     */
    public CheckresultExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkresult
     *
     * @mbggenerated Wed Feb 20 16:43:50 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkresult
     *
     * @mbggenerated Wed Feb 20 16:43:50 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkresult
     *
     * @mbggenerated Wed Feb 20 16:43:50 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkresult
     *
     * @mbggenerated Wed Feb 20 16:43:50 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkresult
     *
     * @mbggenerated Wed Feb 20 16:43:50 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkresult
     *
     * @mbggenerated Wed Feb 20 16:43:50 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkresult
     *
     * @mbggenerated Wed Feb 20 16:43:50 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkresult
     *
     * @mbggenerated Wed Feb 20 16:43:50 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkresult
     *
     * @mbggenerated Wed Feb 20 16:43:50 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkresult
     *
     * @mbggenerated Wed Feb 20 16:43:50 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table checkresult
     *
     * @mbggenerated Wed Feb 20 16:43:50 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCridIsNull() {
            addCriterion("crid is null");
            return (Criteria) this;
        }

        public Criteria andCridIsNotNull() {
            addCriterion("crid is not null");
            return (Criteria) this;
        }

        public Criteria andCridEqualTo(Integer value) {
            addCriterion("crid =", value, "crid");
            return (Criteria) this;
        }

        public Criteria andCridNotEqualTo(Integer value) {
            addCriterion("crid <>", value, "crid");
            return (Criteria) this;
        }

        public Criteria andCridGreaterThan(Integer value) {
            addCriterion("crid >", value, "crid");
            return (Criteria) this;
        }

        public Criteria andCridGreaterThanOrEqualTo(Integer value) {
            addCriterion("crid >=", value, "crid");
            return (Criteria) this;
        }

        public Criteria andCridLessThan(Integer value) {
            addCriterion("crid <", value, "crid");
            return (Criteria) this;
        }

        public Criteria andCridLessThanOrEqualTo(Integer value) {
            addCriterion("crid <=", value, "crid");
            return (Criteria) this;
        }

        public Criteria andCridIn(List<Integer> values) {
            addCriterion("crid in", values, "crid");
            return (Criteria) this;
        }

        public Criteria andCridNotIn(List<Integer> values) {
            addCriterion("crid not in", values, "crid");
            return (Criteria) this;
        }

        public Criteria andCridBetween(Integer value1, Integer value2) {
            addCriterion("crid between", value1, value2, "crid");
            return (Criteria) this;
        }

        public Criteria andCridNotBetween(Integer value1, Integer value2) {
            addCriterion("crid not between", value1, value2, "crid");
            return (Criteria) this;
        }

        public Criteria andUidIsNull() {
            addCriterion("uid is null");
            return (Criteria) this;
        }

        public Criteria andUidIsNotNull() {
            addCriterion("uid is not null");
            return (Criteria) this;
        }

        public Criteria andUidEqualTo(Integer value) {
            addCriterion("uid =", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotEqualTo(Integer value) {
            addCriterion("uid <>", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThan(Integer value) {
            addCriterion("uid >", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThanOrEqualTo(Integer value) {
            addCriterion("uid >=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThan(Integer value) {
            addCriterion("uid <", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThanOrEqualTo(Integer value) {
            addCriterion("uid <=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidIn(List<Integer> values) {
            addCriterion("uid in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotIn(List<Integer> values) {
            addCriterion("uid not in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidBetween(Integer value1, Integer value2) {
            addCriterion("uid between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotBetween(Integer value1, Integer value2) {
            addCriterion("uid not between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andChtimeIsNull() {
            addCriterion("chtime is null");
            return (Criteria) this;
        }

        public Criteria andChtimeIsNotNull() {
            addCriterion("chtime is not null");
            return (Criteria) this;
        }

        public Criteria andChtimeEqualTo(Date value) {
            addCriterion("chtime =", value, "chtime");
            return (Criteria) this;
        }

        public Criteria andChtimeNotEqualTo(Date value) {
            addCriterion("chtime <>", value, "chtime");
            return (Criteria) this;
        }

        public Criteria andChtimeGreaterThan(Date value) {
            addCriterion("chtime >", value, "chtime");
            return (Criteria) this;
        }

        public Criteria andChtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("chtime >=", value, "chtime");
            return (Criteria) this;
        }

        public Criteria andChtimeLessThan(Date value) {
            addCriterion("chtime <", value, "chtime");
            return (Criteria) this;
        }

        public Criteria andChtimeLessThanOrEqualTo(Date value) {
            addCriterion("chtime <=", value, "chtime");
            return (Criteria) this;
        }

        public Criteria andChtimeIn(List<Date> values) {
            addCriterion("chtime in", values, "chtime");
            return (Criteria) this;
        }

        public Criteria andChtimeNotIn(List<Date> values) {
            addCriterion("chtime not in", values, "chtime");
            return (Criteria) this;
        }

        public Criteria andChtimeBetween(Date value1, Date value2) {
            addCriterion("chtime between", value1, value2, "chtime");
            return (Criteria) this;
        }

        public Criteria andChtimeNotBetween(Date value1, Date value2) {
            addCriterion("chtime not between", value1, value2, "chtime");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andChidIsNull() {
            addCriterion("chid is null");
            return (Criteria) this;
        }

        public Criteria andChidIsNotNull() {
            addCriterion("chid is not null");
            return (Criteria) this;
        }

        public Criteria andChidEqualTo(Integer value) {
            addCriterion("chid =", value, "chid");
            return (Criteria) this;
        }

        public Criteria andChidNotEqualTo(Integer value) {
            addCriterion("chid <>", value, "chid");
            return (Criteria) this;
        }

        public Criteria andChidGreaterThan(Integer value) {
            addCriterion("chid >", value, "chid");
            return (Criteria) this;
        }

        public Criteria andChidGreaterThanOrEqualTo(Integer value) {
            addCriterion("chid >=", value, "chid");
            return (Criteria) this;
        }

        public Criteria andChidLessThan(Integer value) {
            addCriterion("chid <", value, "chid");
            return (Criteria) this;
        }

        public Criteria andChidLessThanOrEqualTo(Integer value) {
            addCriterion("chid <=", value, "chid");
            return (Criteria) this;
        }

        public Criteria andChidIn(List<Integer> values) {
            addCriterion("chid in", values, "chid");
            return (Criteria) this;
        }

        public Criteria andChidNotIn(List<Integer> values) {
            addCriterion("chid not in", values, "chid");
            return (Criteria) this;
        }

        public Criteria andChidBetween(Integer value1, Integer value2) {
            addCriterion("chid between", value1, value2, "chid");
            return (Criteria) this;
        }

        public Criteria andChidNotBetween(Integer value1, Integer value2) {
            addCriterion("chid not between", value1, value2, "chid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table checkresult
     *
     * @mbggenerated do_not_delete_during_merge Wed Feb 20 16:43:50 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table checkresult
     *
     * @mbggenerated Wed Feb 20 16:43:50 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}