package com.my.pojo;

import java.util.Date;

public class Checkin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checkin.chid
     *
     * @mbggenerated Fri Mar 29 21:57:02 CST 2019
     */
    private Integer chid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checkin.courseid
     *
     * @mbggenerated Fri Mar 29 21:57:02 CST 2019
     */
    private Integer courseid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checkin.isopen
     *
     * @mbggenerated Fri Mar 29 21:57:02 CST 2019
     */
    private String isopen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checkin.checkcode
     *
     * @mbggenerated Fri Mar 29 21:57:02 CST 2019
     */
    private String checkcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checkin.checktime
     *
     * @mbggenerated Fri Mar 29 21:57:02 CST 2019
     */
    private Date checktime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checkin.chid
     *
     * @return the value of checkin.chid
     *
     * @mbggenerated Fri Mar 29 21:57:02 CST 2019
     */
    public Integer getChid() {
        return chid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checkin.chid
     *
     * @param chid the value for checkin.chid
     *
     * @mbggenerated Fri Mar 29 21:57:02 CST 2019
     */
    public void setChid(Integer chid) {
        this.chid = chid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checkin.courseid
     *
     * @return the value of checkin.courseid
     *
     * @mbggenerated Fri Mar 29 21:57:02 CST 2019
     */
    public Integer getCourseid() {
        return courseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checkin.courseid
     *
     * @param courseid the value for checkin.courseid
     *
     * @mbggenerated Fri Mar 29 21:57:02 CST 2019
     */
    public void setCourseid(Integer courseid) {
        this.courseid = courseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checkin.isopen
     *
     * @return the value of checkin.isopen
     *
     * @mbggenerated Fri Mar 29 21:57:02 CST 2019
     */
    public String getIsopen() {
        return isopen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checkin.isopen
     *
     * @param isopen the value for checkin.isopen
     *
     * @mbggenerated Fri Mar 29 21:57:02 CST 2019
     */
    public void setIsopen(String isopen) {
        this.isopen = isopen == null ? null : isopen.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checkin.checkcode
     *
     * @return the value of checkin.checkcode
     *
     * @mbggenerated Fri Mar 29 21:57:02 CST 2019
     */
    public String getCheckcode() {
        return checkcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checkin.checkcode
     *
     * @param checkcode the value for checkin.checkcode
     *
     * @mbggenerated Fri Mar 29 21:57:02 CST 2019
     */
    public void setCheckcode(String checkcode) {
        this.checkcode = checkcode == null ? null : checkcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checkin.checktime
     *
     * @return the value of checkin.checktime
     *
     * @mbggenerated Fri Mar 29 21:57:02 CST 2019
     */
    public Date getChecktime() {
        return checktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checkin.checktime
     *
     * @param checktime the value for checkin.checktime
     *
     * @mbggenerated Fri Mar 29 21:57:02 CST 2019
     */
    public void setChecktime(Date checktime) {
        this.checktime = checktime;
    }
}