package com.my.pojo;

import java.util.Date;

public class Homework {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homework.hid
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    private Integer hid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homework.cid
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    private String cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homework.question
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    private String question;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homework.starttime
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    private Date starttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homework.endtime
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    private Date endtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homework.status
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homework.hid
     *
     * @return the value of homework.hid
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public Integer getHid() {
        return hid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homework.hid
     *
     * @param hid the value for homework.hid
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public void setHid(Integer hid) {
        this.hid = hid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homework.cid
     *
     * @return the value of homework.cid
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public String getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homework.cid
     *
     * @param cid the value for homework.cid
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public void setCid(String cid) {
        this.cid = cid == null ? null : cid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homework.question
     *
     * @return the value of homework.question
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public String getQuestion() {
        return question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homework.question
     *
     * @param question the value for homework.question
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public void setQuestion(String question) {
        this.question = question == null ? null : question.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homework.starttime
     *
     * @return the value of homework.starttime
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homework.starttime
     *
     * @param starttime the value for homework.starttime
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homework.endtime
     *
     * @return the value of homework.endtime
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homework.endtime
     *
     * @param endtime the value for homework.endtime
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homework.status
     *
     * @return the value of homework.status
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homework.status
     *
     * @param status the value for homework.status
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}