package com.my.pojo;

public class Homeworkresult {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homeworkresult.hrid
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    private Integer hrid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homeworkresult.uid
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homeworkresult.hid
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    private Integer hid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homeworkresult.answer
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    private String answer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homeworkresult.value
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    private Integer value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homeworkresult.hrid
     *
     * @return the value of homeworkresult.hrid
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public Integer getHrid() {
        return hrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homeworkresult.hrid
     *
     * @param hrid the value for homeworkresult.hrid
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public void setHrid(Integer hrid) {
        this.hrid = hrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homeworkresult.uid
     *
     * @return the value of homeworkresult.uid
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homeworkresult.uid
     *
     * @param uid the value for homeworkresult.uid
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homeworkresult.hid
     *
     * @return the value of homeworkresult.hid
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public Integer getHid() {
        return hid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homeworkresult.hid
     *
     * @param hid the value for homeworkresult.hid
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public void setHid(Integer hid) {
        this.hid = hid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homeworkresult.answer
     *
     * @return the value of homeworkresult.answer
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homeworkresult.answer
     *
     * @param answer the value for homeworkresult.answer
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public void setAnswer(String answer) {
        this.answer = answer == null ? null : answer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homeworkresult.value
     *
     * @return the value of homeworkresult.value
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public Integer getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homeworkresult.value
     *
     * @param value the value for homeworkresult.value
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public void setValue(Integer value) {
        this.value = value;
    }
}