package com.my.pojo;

public class Member {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.mid
     *
     * @mbggenerated Mon Feb 25 13:03:42 CST 2019
     */
    private Integer mid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.uid
     *
     * @mbggenerated Mon Feb 25 13:03:42 CST 2019
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.name
     *
     * @mbggenerated Mon Feb 25 13:03:42 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.role
     *
     * @mbggenerated Mon Feb 25 13:03:42 CST 2019
     */
    private String role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.cid
     *
     * @mbggenerated Mon Feb 25 13:03:42 CST 2019
     */
    private Integer cid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.mid
     *
     * @return the value of member.mid
     *
     * @mbggenerated Mon Feb 25 13:03:42 CST 2019
     */
    public Integer getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.mid
     *
     * @param mid the value for member.mid
     *
     * @mbggenerated Mon Feb 25 13:03:42 CST 2019
     */
    public void setMid(Integer mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.uid
     *
     * @return the value of member.uid
     *
     * @mbggenerated Mon Feb 25 13:03:42 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.uid
     *
     * @param uid the value for member.uid
     *
     * @mbggenerated Mon Feb 25 13:03:42 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.name
     *
     * @return the value of member.name
     *
     * @mbggenerated Mon Feb 25 13:03:42 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.name
     *
     * @param name the value for member.name
     *
     * @mbggenerated Mon Feb 25 13:03:42 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.role
     *
     * @return the value of member.role
     *
     * @mbggenerated Mon Feb 25 13:03:42 CST 2019
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.role
     *
     * @param role the value for member.role
     *
     * @mbggenerated Mon Feb 25 13:03:42 CST 2019
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.cid
     *
     * @return the value of member.cid
     *
     * @mbggenerated Mon Feb 25 13:03:42 CST 2019
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.cid
     *
     * @param cid the value for member.cid
     *
     * @mbggenerated Mon Feb 25 13:03:42 CST 2019
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }
}