package com.my.pojo;

public class Message {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.mid
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    private Integer mid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.cid
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    private Integer cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.sender
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    private Integer sender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.reveiver
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    private Integer reveiver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.content
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.mid
     *
     * @return the value of message.mid
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public Integer getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.mid
     *
     * @param mid the value for message.mid
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public void setMid(Integer mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.cid
     *
     * @return the value of message.cid
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.cid
     *
     * @param cid the value for message.cid
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.sender
     *
     * @return the value of message.sender
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public Integer getSender() {
        return sender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.sender
     *
     * @param sender the value for message.sender
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public void setSender(Integer sender) {
        this.sender = sender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.reveiver
     *
     * @return the value of message.reveiver
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public Integer getReveiver() {
        return reveiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.reveiver
     *
     * @param reveiver the value for message.reveiver
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public void setReveiver(Integer reveiver) {
        this.reveiver = reveiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.content
     *
     * @return the value of message.content
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.content
     *
     * @param content the value for message.content
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}