package com.my.pojo;

public class Questionbank {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questionbank.qbid
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    private Integer qbid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questionbank.qid
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    private Integer qid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questionbank.question
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    private String question;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questionbank.value
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    private Integer value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questionbank.testid
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    private Integer testid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questionbank.qbid
     *
     * @return the value of questionbank.qbid
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public Integer getQbid() {
        return qbid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questionbank.qbid
     *
     * @param qbid the value for questionbank.qbid
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public void setQbid(Integer qbid) {
        this.qbid = qbid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questionbank.qid
     *
     * @return the value of questionbank.qid
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public Integer getQid() {
        return qid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questionbank.qid
     *
     * @param qid the value for questionbank.qid
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public void setQid(Integer qid) {
        this.qid = qid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questionbank.question
     *
     * @return the value of questionbank.question
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public String getQuestion() {
        return question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questionbank.question
     *
     * @param question the value for questionbank.question
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public void setQuestion(String question) {
        this.question = question == null ? null : question.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questionbank.value
     *
     * @return the value of questionbank.value
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public Integer getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questionbank.value
     *
     * @param value the value for questionbank.value
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public void setValue(Integer value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questionbank.testid
     *
     * @return the value of questionbank.testid
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public Integer getTestid() {
        return testid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questionbank.testid
     *
     * @param testid the value for questionbank.testid
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public void setTestid(Integer testid) {
        this.testid = testid;
    }
}