package com.my.pojo;

public class Questionoption {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questionoption.qoid
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    private Integer qoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questionoption.qbid
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    private Integer qbid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questionoption.content
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questionoption.iscorrect
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    private String iscorrect;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questionoption.qoid
     *
     * @return the value of questionoption.qoid
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public Integer getQoid() {
        return qoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questionoption.qoid
     *
     * @param qoid the value for questionoption.qoid
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public void setQoid(Integer qoid) {
        this.qoid = qoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questionoption.qbid
     *
     * @return the value of questionoption.qbid
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public Integer getQbid() {
        return qbid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questionoption.qbid
     *
     * @param qbid the value for questionoption.qbid
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public void setQbid(Integer qbid) {
        this.qbid = qbid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questionoption.content
     *
     * @return the value of questionoption.content
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questionoption.content
     *
     * @param content the value for questionoption.content
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questionoption.iscorrect
     *
     * @return the value of questionoption.iscorrect
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public String getIscorrect() {
        return iscorrect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questionoption.iscorrect
     *
     * @param iscorrect the value for questionoption.iscorrect
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public void setIscorrect(String iscorrect) {
        this.iscorrect = iscorrect == null ? null : iscorrect.trim();
    }
}