package com.my.pojo;

public class ResourcesClass {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resources_class.rcid
     *
     * @mbggenerated Wed Mar 06 12:16:43 CST 2019
     */
    private Integer rcid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resources_class.rid
     *
     * @mbggenerated Wed Mar 06 12:16:43 CST 2019
     */
    private Integer rid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resources_class.cid
     *
     * @mbggenerated Wed Mar 06 12:16:43 CST 2019
     */
    private Integer cid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resources_class.rcid
     *
     * @return the value of resources_class.rcid
     *
     * @mbggenerated Wed Mar 06 12:16:43 CST 2019
     */
    public Integer getRcid() {
        return rcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resources_class.rcid
     *
     * @param rcid the value for resources_class.rcid
     *
     * @mbggenerated Wed Mar 06 12:16:43 CST 2019
     */
    public void setRcid(Integer rcid) {
        this.rcid = rcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resources_class.rid
     *
     * @return the value of resources_class.rid
     *
     * @mbggenerated Wed Mar 06 12:16:43 CST 2019
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resources_class.rid
     *
     * @param rid the value for resources_class.rid
     *
     * @mbggenerated Wed Mar 06 12:16:43 CST 2019
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resources_class.cid
     *
     * @return the value of resources_class.cid
     *
     * @mbggenerated Wed Mar 06 12:16:43 CST 2019
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resources_class.cid
     *
     * @param cid the value for resources_class.cid
     *
     * @mbggenerated Wed Mar 06 12:16:43 CST 2019
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }
}