package com.my.pojo;

public class Testresult {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testresult.trid
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    private Integer trid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testresult.uid
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testresult.tid
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    private Integer tid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testresult.score
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    private Integer score;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testresult.trid
     *
     * @return the value of testresult.trid
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public Integer getTrid() {
        return trid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testresult.trid
     *
     * @param trid the value for testresult.trid
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public void setTrid(Integer trid) {
        this.trid = trid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testresult.uid
     *
     * @return the value of testresult.uid
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testresult.uid
     *
     * @param uid the value for testresult.uid
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testresult.tid
     *
     * @return the value of testresult.tid
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testresult.tid
     *
     * @param tid the value for testresult.tid
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testresult.score
     *
     * @return the value of testresult.score
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testresult.score
     *
     * @param score the value for testresult.score
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public void setScore(Integer score) {
        this.score = score;
    }
}