package com.my.pojo;

import java.util.Date;

public class Test {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.tid
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    private Integer tid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.cid
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    private String cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.starttime
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    private Date starttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.endtime
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    private Date endtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.status
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.time
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    private Integer time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.total
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    private Integer total;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.tid
     *
     * @return the value of test.tid
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.tid
     *
     * @param tid the value for test.tid
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.cid
     *
     * @return the value of test.cid
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public String getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.cid
     *
     * @param cid the value for test.cid
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public void setCid(String cid) {
        this.cid = cid == null ? null : cid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.starttime
     *
     * @return the value of test.starttime
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.starttime
     *
     * @param starttime the value for test.starttime
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.endtime
     *
     * @return the value of test.endtime
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.endtime
     *
     * @param endtime the value for test.endtime
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.status
     *
     * @return the value of test.status
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.status
     *
     * @param status the value for test.status
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.time
     *
     * @return the value of test.time
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public Integer getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.time
     *
     * @param time the value for test.time
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public void setTime(Integer time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.total
     *
     * @return the value of test.total
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public Integer getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.total
     *
     * @param total the value for test.total
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public void setTotal(Integer total) {
        this.total = total;
    }
}