package com.my.pojo;

public class Users {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.uid
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.email
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.name
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.password
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.phone
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.gender
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.yob
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    private Integer yob;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.code
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    private String code;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.uid
     *
     * @return the value of users.uid
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.uid
     *
     * @param uid the value for users.uid
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.email
     *
     * @return the value of users.email
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.email
     *
     * @param email the value for users.email
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.name
     *
     * @return the value of users.name
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.name
     *
     * @param name the value for users.name
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.password
     *
     * @return the value of users.password
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.password
     *
     * @param password the value for users.password
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.phone
     *
     * @return the value of users.phone
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.phone
     *
     * @param phone the value for users.phone
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.gender
     *
     * @return the value of users.gender
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.gender
     *
     * @param gender the value for users.gender
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.yob
     *
     * @return the value of users.yob
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public Integer getYob() {
        return yob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.yob
     *
     * @param yob the value for users.yob
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public void setYob(Integer yob) {
        this.yob = yob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.code
     *
     * @return the value of users.code
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.code
     *
     * @param code the value for users.code
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }
}