package com.my.pojo;

public class Voteoption {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column voteoption.void
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    private Integer void;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column voteoption.vbid
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    private Integer vbid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column voteoption.content
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voteoption.void
     *
     * @return the value of voteoption.void
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public Integer getVoid() {
        return void;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voteoption.void
     *
     * @param void the value for voteoption.void
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public void setVoid(Integer void) {
        this.void = void;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voteoption.vbid
     *
     * @return the value of voteoption.vbid
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public Integer getVbid() {
        return vbid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voteoption.vbid
     *
     * @param vbid the value for voteoption.vbid
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public void setVbid(Integer vbid) {
        this.vbid = vbid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voteoption.content
     *
     * @return the value of voteoption.content
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voteoption.content
     *
     * @param content the value for voteoption.content
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}