package com.my.pojo;

import java.util.ArrayList;
import java.util.List;

public class VoteoptionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table voteoption
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table voteoption
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table voteoption
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteoption
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public VoteoptionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteoption
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteoption
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteoption
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteoption
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteoption
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteoption
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteoption
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteoption
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteoption
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteoption
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table voteoption
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andVoidIsNull() {
            addCriterion("void is null");
            return (Criteria) this;
        }

        public Criteria andVoidIsNotNull() {
            addCriterion("void is not null");
            return (Criteria) this;
        }

        public Criteria andVoidEqualTo(Integer value) {
            addCriterion("void =", value, "void");
            return (Criteria) this;
        }

        public Criteria andVoidNotEqualTo(Integer value) {
            addCriterion("void <>", value, "void");
            return (Criteria) this;
        }

        public Criteria andVoidGreaterThan(Integer value) {
            addCriterion("void >", value, "void");
            return (Criteria) this;
        }

        public Criteria andVoidGreaterThanOrEqualTo(Integer value) {
            addCriterion("void >=", value, "void");
            return (Criteria) this;
        }

        public Criteria andVoidLessThan(Integer value) {
            addCriterion("void <", value, "void");
            return (Criteria) this;
        }

        public Criteria andVoidLessThanOrEqualTo(Integer value) {
            addCriterion("void <=", value, "void");
            return (Criteria) this;
        }

        public Criteria andVoidIn(List<Integer> values) {
            addCriterion("void in", values, "void");
            return (Criteria) this;
        }

        public Criteria andVoidNotIn(List<Integer> values) {
            addCriterion("void not in", values, "void");
            return (Criteria) this;
        }

        public Criteria andVoidBetween(Integer value1, Integer value2) {
            addCriterion("void between", value1, value2, "void");
            return (Criteria) this;
        }

        public Criteria andVoidNotBetween(Integer value1, Integer value2) {
            addCriterion("void not between", value1, value2, "void");
            return (Criteria) this;
        }

        public Criteria andVbidIsNull() {
            addCriterion("vbid is null");
            return (Criteria) this;
        }

        public Criteria andVbidIsNotNull() {
            addCriterion("vbid is not null");
            return (Criteria) this;
        }

        public Criteria andVbidEqualTo(Integer value) {
            addCriterion("vbid =", value, "vbid");
            return (Criteria) this;
        }

        public Criteria andVbidNotEqualTo(Integer value) {
            addCriterion("vbid <>", value, "vbid");
            return (Criteria) this;
        }

        public Criteria andVbidGreaterThan(Integer value) {
            addCriterion("vbid >", value, "vbid");
            return (Criteria) this;
        }

        public Criteria andVbidGreaterThanOrEqualTo(Integer value) {
            addCriterion("vbid >=", value, "vbid");
            return (Criteria) this;
        }

        public Criteria andVbidLessThan(Integer value) {
            addCriterion("vbid <", value, "vbid");
            return (Criteria) this;
        }

        public Criteria andVbidLessThanOrEqualTo(Integer value) {
            addCriterion("vbid <=", value, "vbid");
            return (Criteria) this;
        }

        public Criteria andVbidIn(List<Integer> values) {
            addCriterion("vbid in", values, "vbid");
            return (Criteria) this;
        }

        public Criteria andVbidNotIn(List<Integer> values) {
            addCriterion("vbid not in", values, "vbid");
            return (Criteria) this;
        }

        public Criteria andVbidBetween(Integer value1, Integer value2) {
            addCriterion("vbid between", value1, value2, "vbid");
            return (Criteria) this;
        }

        public Criteria andVbidNotBetween(Integer value1, Integer value2) {
            addCriterion("vbid not between", value1, value2, "vbid");
            return (Criteria) this;
        }

        public Criteria andContentIsNull() {
            addCriterion("content is null");
            return (Criteria) this;
        }

        public Criteria andContentIsNotNull() {
            addCriterion("content is not null");
            return (Criteria) this;
        }

        public Criteria andContentEqualTo(String value) {
            addCriterion("content =", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotEqualTo(String value) {
            addCriterion("content <>", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThan(String value) {
            addCriterion("content >", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThanOrEqualTo(String value) {
            addCriterion("content >=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThan(String value) {
            addCriterion("content <", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThanOrEqualTo(String value) {
            addCriterion("content <=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLike(String value) {
            addCriterion("content like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotLike(String value) {
            addCriterion("content not like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentIn(List<String> values) {
            addCriterion("content in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotIn(List<String> values) {
            addCriterion("content not in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentBetween(String value1, String value2) {
            addCriterion("content between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotBetween(String value1, String value2) {
            addCriterion("content not between", value1, value2, "content");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table voteoption
     *
     * @mbggenerated do_not_delete_during_merge Tue Feb 19 19:39:03 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table voteoption
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}