package com.my.pojo;

public class Voteresult {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column voteresult.vrid
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    private Integer vrid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column voteresult.uid
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column voteresult.vid
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    private Integer vid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column voteresult.answer
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    private String answer;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voteresult.vrid
     *
     * @return the value of voteresult.vrid
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public Integer getVrid() {
        return vrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voteresult.vrid
     *
     * @param vrid the value for voteresult.vrid
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public void setVrid(Integer vrid) {
        this.vrid = vrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voteresult.uid
     *
     * @return the value of voteresult.uid
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voteresult.uid
     *
     * @param uid the value for voteresult.uid
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voteresult.vid
     *
     * @return the value of voteresult.vid
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public Integer getVid() {
        return vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voteresult.vid
     *
     * @param vid the value for voteresult.vid
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public void setVid(Integer vid) {
        this.vid = vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voteresult.answer
     *
     * @return the value of voteresult.answer
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voteresult.answer
     *
     * @param answer the value for voteresult.answer
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public void setAnswer(String answer) {
        this.answer = answer == null ? null : answer.trim();
    }
}