package com.my.pojo;

public class Votebank {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column votebank.vbid
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    private Integer vbid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column votebank.qid
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    private Integer qid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column votebank.question
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    private String question;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column votebank.voteid
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    private Integer voteid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column votebank.vbid
     *
     * @return the value of votebank.vbid
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public Integer getVbid() {
        return vbid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column votebank.vbid
     *
     * @param vbid the value for votebank.vbid
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public void setVbid(Integer vbid) {
        this.vbid = vbid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column votebank.qid
     *
     * @return the value of votebank.qid
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public Integer getQid() {
        return qid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column votebank.qid
     *
     * @param qid the value for votebank.qid
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public void setQid(Integer qid) {
        this.qid = qid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column votebank.question
     *
     * @return the value of votebank.question
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public String getQuestion() {
        return question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column votebank.question
     *
     * @param question the value for votebank.question
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public void setQuestion(String question) {
        this.question = question == null ? null : question.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column votebank.voteid
     *
     * @return the value of votebank.voteid
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public Integer getVoteid() {
        return voteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column votebank.voteid
     *
     * @param voteid the value for votebank.voteid
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public void setVoteid(Integer voteid) {
        this.voteid = voteid;
    }
}