package com.my.pojo;

import java.util.ArrayList;
import java.util.List;

public class VotebankExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table votebank
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table votebank
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table votebank
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votebank
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public VotebankExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votebank
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votebank
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votebank
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votebank
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votebank
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votebank
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votebank
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votebank
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votebank
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votebank
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table votebank
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andVbidIsNull() {
            addCriterion("vbid is null");
            return (Criteria) this;
        }

        public Criteria andVbidIsNotNull() {
            addCriterion("vbid is not null");
            return (Criteria) this;
        }

        public Criteria andVbidEqualTo(Integer value) {
            addCriterion("vbid =", value, "vbid");
            return (Criteria) this;
        }

        public Criteria andVbidNotEqualTo(Integer value) {
            addCriterion("vbid <>", value, "vbid");
            return (Criteria) this;
        }

        public Criteria andVbidGreaterThan(Integer value) {
            addCriterion("vbid >", value, "vbid");
            return (Criteria) this;
        }

        public Criteria andVbidGreaterThanOrEqualTo(Integer value) {
            addCriterion("vbid >=", value, "vbid");
            return (Criteria) this;
        }

        public Criteria andVbidLessThan(Integer value) {
            addCriterion("vbid <", value, "vbid");
            return (Criteria) this;
        }

        public Criteria andVbidLessThanOrEqualTo(Integer value) {
            addCriterion("vbid <=", value, "vbid");
            return (Criteria) this;
        }

        public Criteria andVbidIn(List<Integer> values) {
            addCriterion("vbid in", values, "vbid");
            return (Criteria) this;
        }

        public Criteria andVbidNotIn(List<Integer> values) {
            addCriterion("vbid not in", values, "vbid");
            return (Criteria) this;
        }

        public Criteria andVbidBetween(Integer value1, Integer value2) {
            addCriterion("vbid between", value1, value2, "vbid");
            return (Criteria) this;
        }

        public Criteria andVbidNotBetween(Integer value1, Integer value2) {
            addCriterion("vbid not between", value1, value2, "vbid");
            return (Criteria) this;
        }

        public Criteria andQidIsNull() {
            addCriterion("qid is null");
            return (Criteria) this;
        }

        public Criteria andQidIsNotNull() {
            addCriterion("qid is not null");
            return (Criteria) this;
        }

        public Criteria andQidEqualTo(Integer value) {
            addCriterion("qid =", value, "qid");
            return (Criteria) this;
        }

        public Criteria andQidNotEqualTo(Integer value) {
            addCriterion("qid <>", value, "qid");
            return (Criteria) this;
        }

        public Criteria andQidGreaterThan(Integer value) {
            addCriterion("qid >", value, "qid");
            return (Criteria) this;
        }

        public Criteria andQidGreaterThanOrEqualTo(Integer value) {
            addCriterion("qid >=", value, "qid");
            return (Criteria) this;
        }

        public Criteria andQidLessThan(Integer value) {
            addCriterion("qid <", value, "qid");
            return (Criteria) this;
        }

        public Criteria andQidLessThanOrEqualTo(Integer value) {
            addCriterion("qid <=", value, "qid");
            return (Criteria) this;
        }

        public Criteria andQidIn(List<Integer> values) {
            addCriterion("qid in", values, "qid");
            return (Criteria) this;
        }

        public Criteria andQidNotIn(List<Integer> values) {
            addCriterion("qid not in", values, "qid");
            return (Criteria) this;
        }

        public Criteria andQidBetween(Integer value1, Integer value2) {
            addCriterion("qid between", value1, value2, "qid");
            return (Criteria) this;
        }

        public Criteria andQidNotBetween(Integer value1, Integer value2) {
            addCriterion("qid not between", value1, value2, "qid");
            return (Criteria) this;
        }

        public Criteria andQuestionIsNull() {
            addCriterion("question is null");
            return (Criteria) this;
        }

        public Criteria andQuestionIsNotNull() {
            addCriterion("question is not null");
            return (Criteria) this;
        }

        public Criteria andQuestionEqualTo(String value) {
            addCriterion("question =", value, "question");
            return (Criteria) this;
        }

        public Criteria andQuestionNotEqualTo(String value) {
            addCriterion("question <>", value, "question");
            return (Criteria) this;
        }

        public Criteria andQuestionGreaterThan(String value) {
            addCriterion("question >", value, "question");
            return (Criteria) this;
        }

        public Criteria andQuestionGreaterThanOrEqualTo(String value) {
            addCriterion("question >=", value, "question");
            return (Criteria) this;
        }

        public Criteria andQuestionLessThan(String value) {
            addCriterion("question <", value, "question");
            return (Criteria) this;
        }

        public Criteria andQuestionLessThanOrEqualTo(String value) {
            addCriterion("question <=", value, "question");
            return (Criteria) this;
        }

        public Criteria andQuestionLike(String value) {
            addCriterion("question like", value, "question");
            return (Criteria) this;
        }

        public Criteria andQuestionNotLike(String value) {
            addCriterion("question not like", value, "question");
            return (Criteria) this;
        }

        public Criteria andQuestionIn(List<String> values) {
            addCriterion("question in", values, "question");
            return (Criteria) this;
        }

        public Criteria andQuestionNotIn(List<String> values) {
            addCriterion("question not in", values, "question");
            return (Criteria) this;
        }

        public Criteria andQuestionBetween(String value1, String value2) {
            addCriterion("question between", value1, value2, "question");
            return (Criteria) this;
        }

        public Criteria andQuestionNotBetween(String value1, String value2) {
            addCriterion("question not between", value1, value2, "question");
            return (Criteria) this;
        }

        public Criteria andVoteidIsNull() {
            addCriterion("voteid is null");
            return (Criteria) this;
        }

        public Criteria andVoteidIsNotNull() {
            addCriterion("voteid is not null");
            return (Criteria) this;
        }

        public Criteria andVoteidEqualTo(Integer value) {
            addCriterion("voteid =", value, "voteid");
            return (Criteria) this;
        }

        public Criteria andVoteidNotEqualTo(Integer value) {
            addCriterion("voteid <>", value, "voteid");
            return (Criteria) this;
        }

        public Criteria andVoteidGreaterThan(Integer value) {
            addCriterion("voteid >", value, "voteid");
            return (Criteria) this;
        }

        public Criteria andVoteidGreaterThanOrEqualTo(Integer value) {
            addCriterion("voteid >=", value, "voteid");
            return (Criteria) this;
        }

        public Criteria andVoteidLessThan(Integer value) {
            addCriterion("voteid <", value, "voteid");
            return (Criteria) this;
        }

        public Criteria andVoteidLessThanOrEqualTo(Integer value) {
            addCriterion("voteid <=", value, "voteid");
            return (Criteria) this;
        }

        public Criteria andVoteidIn(List<Integer> values) {
            addCriterion("voteid in", values, "voteid");
            return (Criteria) this;
        }

        public Criteria andVoteidNotIn(List<Integer> values) {
            addCriterion("voteid not in", values, "voteid");
            return (Criteria) this;
        }

        public Criteria andVoteidBetween(Integer value1, Integer value2) {
            addCriterion("voteid between", value1, value2, "voteid");
            return (Criteria) this;
        }

        public Criteria andVoteidNotBetween(Integer value1, Integer value2) {
            addCriterion("voteid not between", value1, value2, "voteid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table votebank
     *
     * @mbggenerated do_not_delete_during_merge Tue Feb 19 19:39:03 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table votebank
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}