package com.my.dao;

import java.util.List;

import com.my.pojo.Checkin;
import com.my.pojo.CheckinExample;
import org.apache.ibatis.annotations.Param;

public interface CheckinMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkin
     *
     * @mbggenerated Fri Mar 29 21:57:02 CST 2019
     */
    int countByExample(CheckinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkin
     *
     * @mbggenerated Fri Mar 29 21:57:02 CST 2019
     */
    int deleteByExample(CheckinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkin
     *
     * @mbggenerated Fri Mar 29 21:57:02 CST 2019
     */
    int deleteByPrimaryKey(Integer chid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkin
     *
     * @mbggenerated Fri Mar 29 21:57:02 CST 2019
     */
    int insert(Checkin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkin
     *
     * @mbggenerated Fri Mar 29 21:57:02 CST 2019
     */
    int insertSelective(Checkin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkin
     *
     * @mbggenerated Fri Mar 29 21:57:02 CST 2019
     */
    List<Checkin> selectByExample(CheckinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkin
     *
     * @mbggenerated Fri Mar 29 21:57:02 CST 2019
     */
    Checkin selectByPrimaryKey(Integer chid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkin
     *
     * @mbggenerated Fri Mar 29 21:57:02 CST 2019
     */
    int updateByExampleSelective(@Param("record") Checkin record, @Param("example") CheckinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkin
     *
     * @mbggenerated Fri Mar 29 21:57:02 CST 2019
     */
    int updateByExample(@Param("record") Checkin record, @Param("example") CheckinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkin
     *
     * @mbggenerated Fri Mar 29 21:57:02 CST 2019
     */
    int updateByPrimaryKeySelective(Checkin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkin
     *
     * @mbggenerated Fri Mar 29 21:57:02 CST 2019
     */
    int updateByPrimaryKey(Checkin record);
}