package com.my.dao;

import com.my.pojo.Checkresult;
import com.my.pojo.CheckresultExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CheckresultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkresult
     *
     * @mbggenerated Wed Feb 20 16:43:50 CST 2019
     */
    int countByExample(CheckresultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkresult
     *
     * @mbggenerated Wed Feb 20 16:43:50 CST 2019
     */
    int deleteByExample(CheckresultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkresult
     *
     * @mbggenerated Wed Feb 20 16:43:50 CST 2019
     */
    int deleteByPrimaryKey(Integer crid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkresult
     *
     * @mbggenerated Wed Feb 20 16:43:50 CST 2019
     */
    int insert(Checkresult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkresult
     *
     * @mbggenerated Wed Feb 20 16:43:50 CST 2019
     */
    int insertSelective(Checkresult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkresult
     *
     * @mbggenerated Wed Feb 20 16:43:50 CST 2019
     */
    List<Checkresult> selectByExample(CheckresultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkresult
     *
     * @mbggenerated Wed Feb 20 16:43:50 CST 2019
     */
    Checkresult selectByPrimaryKey(Integer crid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkresult
     *
     * @mbggenerated Wed Feb 20 16:43:50 CST 2019
     */
    int updateByExampleSelective(@Param("record") Checkresult record, @Param("example") CheckresultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkresult
     *
     * @mbggenerated Wed Feb 20 16:43:50 CST 2019
     */
    int updateByExample(@Param("record") Checkresult record, @Param("example") CheckresultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkresult
     *
     * @mbggenerated Wed Feb 20 16:43:50 CST 2019
     */
    int updateByPrimaryKeySelective(Checkresult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkresult
     *
     * @mbggenerated Wed Feb 20 16:43:50 CST 2019
     */
    int updateByPrimaryKey(Checkresult record);
}