package com.my.dao;

import com.my.pojo.Questionoption;
import com.my.pojo.QuestionoptionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QuestionoptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionoption
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    int countByExample(QuestionoptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionoption
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    int deleteByExample(QuestionoptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionoption
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    int deleteByPrimaryKey(Integer qoid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionoption
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    int insert(Questionoption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionoption
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    int insertSelective(Questionoption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionoption
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    List<Questionoption> selectByExample(QuestionoptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionoption
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    Questionoption selectByPrimaryKey(Integer qoid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionoption
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    int updateByExampleSelective(@Param("record") Questionoption record, @Param("example") QuestionoptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionoption
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    int updateByExample(@Param("record") Questionoption record, @Param("example") QuestionoptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionoption
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    int updateByPrimaryKeySelective(Questionoption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questionoption
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    int updateByPrimaryKey(Questionoption record);
}