package com.my.dao;

import com.my.pojo.Testresult;
import com.my.pojo.TestresultExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TestresultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testresult
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    int countByExample(TestresultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testresult
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    int deleteByExample(TestresultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testresult
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    int deleteByPrimaryKey(Integer trid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testresult
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    int insert(Testresult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testresult
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    int insertSelective(Testresult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testresult
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    List<Testresult> selectByExample(TestresultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testresult
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    Testresult selectByPrimaryKey(Integer trid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testresult
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    int updateByExampleSelective(@Param("record") Testresult record, @Param("example") TestresultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testresult
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    int updateByExample(@Param("record") Testresult record, @Param("example") TestresultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testresult
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    int updateByPrimaryKeySelective(Testresult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table testresult
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    int updateByPrimaryKey(Testresult record);
}