package com.my.dao;

import com.my.pojo.Voteoption;
import com.my.pojo.VoteoptionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VoteoptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteoption
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    int countByExample(VoteoptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteoption
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    int deleteByExample(VoteoptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteoption
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    int deleteByPrimaryKey(Integer void);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteoption
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    int insert(Voteoption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteoption
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    int insertSelective(Voteoption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteoption
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    List<Voteoption> selectByExample(VoteoptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteoption
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    Voteoption selectByPrimaryKey(Integer void);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteoption
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    int updateByExampleSelective(@Param("record") Voteoption record, @Param("example") VoteoptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteoption
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    int updateByExample(@Param("record") Voteoption record, @Param("example") VoteoptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteoption
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    int updateByPrimaryKeySelective(Voteoption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteoption
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    int updateByPrimaryKey(Voteoption record);
}