package com.my.dao;

import com.my.pojo.Voteresult;
import com.my.pojo.VoteresultExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VoteresultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteresult
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    int countByExample(VoteresultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteresult
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    int deleteByExample(VoteresultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteresult
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    int deleteByPrimaryKey(Integer vrid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteresult
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    int insert(Voteresult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteresult
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    int insertSelective(Voteresult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteresult
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    List<Voteresult> selectByExample(VoteresultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteresult
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    Voteresult selectByPrimaryKey(Integer vrid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteresult
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    int updateByExampleSelective(@Param("record") Voteresult record, @Param("example") VoteresultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteresult
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    int updateByExample(@Param("record") Voteresult record, @Param("example") VoteresultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteresult
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    int updateByPrimaryKeySelective(Voteresult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voteresult
     *
     * @mbggenerated Tue Feb 19 19:39:03 CST 2019
     */
    int updateByPrimaryKey(Voteresult record);
}